# 服务器前置任务(ubuntu使用 Centos项目注释或删掉)
# - name: main
#   hosts: all
#   become: yes
#   become_method: sudo
#   gather_facts: False
#   pre_tasks:
#     - name: Install Python
#       raw: sudo apt update && sudo apt-get -y install python
#       ignore_errors: yes
  
# 核心任务

- name: mediawiki
  hosts: all
  become: yes
  become_method: sudo
  vars_files:
    - vars/main.yml

  roles:
    - role: role_common
    - role: role_cloud
    - role: role_apache
    - role: role_mysql
    - role: role_php-fpm
    - role: role_inotify_watch
    - role: role_lamp
    - role: role_init_password
    - role: role_phpmyadmin
    - role: role_9panel
    - role: mediawiki
    - role: role_end
    
