#Web服务器：apache | nginx，通过交互式选择获取
mediawiki_webs: apache

mediawiki_vhost_dir: /etc/httpd/vhost
mediawiki_vhost_src: vhost.conf
mediawiki_service: httpd
mediawiki_owner: apache
mediawiki_name: "mediawiki"
mediawiki_title: "MediaWiki"
mediawiki_download_url: "https://github.com/wikimedia/mediawiki.git"
mediawiki_version: "1.34.0"  #版本号需定期维护