#MediaWiki版本，需定期维护
mediawiki_version: RHEL1_34

#Web服务器：apache | nginx，通过交互式选择获取
mediawiki_webs: apache

#Nextcloud安装元数据，适用于在不同的环境下安装

mediawiki_runtime_meta:
  CentOS:
    apache:
      vhost_dir: /etc/httpd/vhost
      vhost_src: vhost.conf
      service: httpd
      owner: apache
    nginx:
      vhost_dir: /etc/nginx/conf.d
      vhost_src: default.conf
      service: nginx
      owner: apache
  Ubuntu:
    apache:
      vhost_dir: /etc/apache2/sites-enabled
      vhost_src: vhost.conf
      service: apache2
      owner: www-data
    nginx:
      host_dir: /etc/nginx/conf.d
      vhost_src: default.conf
      service: nginx
      owner: www-data

mediawiki_vhost_dir: mediawiki_runtime_meta.{{ansible_distribution}}.{{mediawiki_webs}}.vhost_dir
mediawiki_vhost_src: mediawiki_runtime_meta.{{ansible_distribution}}.{{mediawiki_webs}}.vhost_src
mediawiki_service: mediawiki_runtime_meta.{{ansible_distribution}}.{{mediawiki_webs}}.service
mediawiki_owner: mediawiki_runtime_meta.{{ansible_distribution}}.{{mediawiki_webs}}.owner