---
# 9panel
- name: Enable 9panel
  lineinfile:
    path: /data/apps/9panel/js/websoft9.js
    regexp: 'var set_apps=\["Example"\];'
    line: 'var set_apps=["Mediawiki"];'

# MediaWiki
- name: Remove example dir
  file:
    path: /data/wwwroot/www.example.com
    state: absent

- name: Create mediawiki directory
  file:
    path: /data/wwwroot/mediawiki
    state: directory
    owner: apache
    group: apache
    mode: 0755

- name: Download MediaWiki
  git:
    repo: 'https://github.com/wikimedia/mediawiki.git'
    dest: /data/wwwroot/mediawiki
    remote: "{{mediawiki_version}}"

- name: Get MySQL Password
  shell: cat /credentials/password.txt | awk 'NR==2' |awk -F ":" '{print $2}'
  register: mysql_password

- name: Create  databases
  mysql_db:
    login_user: root
    login_password: '{{mysql_password.stdout}}'
    name: mediawiki
    state: present

- name: Install PHP-Apcu
  yum:
    name:  php-pecl-apcu
    state: latest
  
# 系统通用
- name: Permission directory
  shell: find /data/wwwroot -type d -exec chmod 750 {} \;
  
- name: Permission file
  shell: find /data/wwwroot -not -type d -exec chmod 640 {} \;

- name: System Upgrade
  yum: name=* state=latest

# 根据不同的基础环境分别处理

- block:
  - name: change owner&group for Apache
    shell: chown -R {{mediawiki_owner}}:{{mediawiki_owner}} /data/wwwroot

  - name: Copy Apache or Nginx vhost configuration
    template: src={{mediawiki_vhost_src}} dest={{mediawiki_vhost_dir}}
    
  - name: restart Apache or Nginx
    service: name={{mediawiki_service}} state=restarted enabled=yes



